import { Product, User } from './types';

// Dummy suppliers for initial data
export const DUMMY_SUPPLIERS: User[] = [
  {
    id: 'supplier-1',
    name: 'Speedy Auto Parts',
    email: 'speedy@example.com',
    phone: '111-222-3333',
    password: 'password123', // For client-side simulation only
    role: 'supplier',
  },
  {
    id: 'supplier-2',
    name: 'Reliable Car Spares',
    email: 'reliable@example.com',
    phone: '444-555-6666',
    password: 'password123', // For client-side simulation only
    role: 'supplier',
  },
];

// Dummy admin
export const DUMMY_ADMIN: User = {
  id: 'admin-1',
  name: 'Admin User',
  email: 'admin@example.com',
  phone: '000-000-0000',
  password: 'adminpassword', // For client-side simulation only
  role: 'admin',
};

// Initial products, now with shopId, shopName, and quantity
export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    partNumber: 'BP-1001',
    name: 'Brake Pad Set (Front)',
    description: 'High-performance ceramic brake pads for superior stopping power and low dust.',
    price: 89.99,
    imageUrl: 'https://picsum.photos/300/200?random=1',
    category: 'Brakes',
    make: 'Toyota',
    model: 'Camry',
    year: 2018,
    vehicleType: 'Sedan',
    shopId: 'supplier-1',
    shopName: DUMMY_SUPPLIERS[0].name,
    quantityAvailable: 10,
  },
  {
    id: '2',
    partNumber: 'OF-2002',
    name: 'Oil Filter (Premium)',
    description: 'Long-life oil filter designed for optimal engine protection and efficiency.',
    price: 15.50,
    imageUrl: 'https://picsum.photos/300/200?random=2',
    category: 'Engine',
    make: 'Honda',
    model: 'CR-V',
    year: 2020,
    vehicleType: 'SUV',
    shopId: 'supplier-2',
    shopName: DUMMY_SUPPLIERS[1].name,
    quantityAvailable: 25,
  },
  {
    id: '3',
    partNumber: 'SA-3003',
    name: 'Shock Absorber (Rear)',
    description: 'Gas-charged shock absorber for improved ride comfort and handling.',
    price: 120.00,
    imageUrl: 'https://picsum.photos/300/200?random=3',
    category: 'Suspension',
    make: 'Ford',
    model: 'F-150',
    year: 2019,
    vehicleType: 'Truck',
    shopId: 'supplier-1',
    shopName: DUMMY_SUPPLIERS[0].name,
    quantityAvailable: 5,
  },
  {
    id: '4',
    partNumber: 'SP-4004',
    name: 'Spark Plug Set (4-pack)',
    description: 'Iridium spark plugs for enhanced ignition and fuel economy.',
    price: 39.95,
    imageUrl: 'https://picsum.photos/300/200?random=4',
    category: 'Engine',
    make: 'Nissan',
    model: 'Versa',
    year: 2017,
    vehicleType: 'Compact',
    shopId: 'supplier-2',
    shopName: DUMMY_SUPPLIERS[1].name,
    quantityAvailable: 15,
  },
  {
    id: '5',
    partNumber: 'WB-5005',
    name: 'Wiper Blade Set (Front)',
    description: 'All-season premium wiper blades for clear visibility in any weather.',
    price: 24.99,
    imageUrl: 'https://picsum.photos/300/200?random=5',
    category: 'Exterior',
    make: 'Toyota',
    model: 'Corolla',
    year: 2021,
    vehicleType: 'Sedan',
    shopId: 'supplier-1',
    shopName: DUMMY_SUPPLIERS[0].name,
    quantityAvailable: 30,
  },
  {
    id: '6',
    partNumber: 'AF-6006',
    name: 'Air Filter (Engine)',
    description: 'High-flow air filter for increased horsepower and engine longevity.',
    price: 29.75,
    imageUrl: 'https://picsum.photos/300/200?random=6',
    category: 'Engine',
    make: 'Jeep',
    model: 'Wrangler',
    year: 2015,
    vehicleType: 'SUV',
    shopId: 'supplier-2',
    shopName: DUMMY_SUPPLIERS[1].name,
    quantityAvailable: 20,
  },
  {
    id: '7',
    partNumber: 'CV-7007',
    name: 'CV Axle Assembly',
    description: 'Complete CV axle assembly for smooth power delivery to wheels.',
    price: 185.00,
    imageUrl: 'https://picsum.photos/300/200?random=7',
    category: 'Drivetrain',
    make: 'Hyundai',
    model: 'Elantra',
    year: 2016,
    vehicleType: 'Sedan',
    shopId: 'supplier-1',
    shopName: DUMMY_SUPPLIERS[0].name,
    quantityAvailable: 7,
  },
  {
    id: '8',
    partNumber: 'AL-8008',
    name: 'Alternator (Remanufactured)',
    description: 'Reliable remanufactured alternator, tested for peak performance.',
    price: 199.99,
    imageUrl: 'https://picsum.photos/300/200?random=8',
    category: 'Electrical',
    make: 'Ram',
    model: '1500',
    year: 2022,
    vehicleType: 'Truck',
    shopId: 'supplier-2',
    shopName: DUMMY_SUPPLIERS[1].name,
    quantityAvailable: 3,
  },
  {
    id: '9',
    partNumber: 'RFM-9009',
    name: 'Radiator Fan Motor',
    description: 'Replacement radiator fan motor for efficient engine cooling.',
    price: 75.25,
    imageUrl: 'https://picsum.photos/300/200?random=9',
    category: 'Cooling',
    make: 'Kia',
    model: 'Forte',
    year: 2019,
    vehicleType: 'Compact',
    shopId: 'supplier-1',
    shopName: DUMMY_SUPPLIERS[0].name,
    quantityAvailable: 12,
  },
  {
    id: '10',
    partNumber: 'WBK-1010',
    name: 'Wheel Bearing Kit',
    description: 'Complete wheel bearing kit for smooth and quiet wheel rotation.',
    price: 65.99,
    imageUrl: 'https://picsum.photos/300/200?random=10',
    category: 'Chassis',
    make: 'Subaru',
    model: 'Forester',
    year: 2018,
    vehicleType: 'SUV',
    shopId: 'supplier-2',
    shopName: DUMMY_SUPPLIERS[1].name,
    quantityAvailable: 8,
  },
  {
    id: '11',
    partNumber: 'HLA-1111',
    name: 'Headlight Assembly (Left)',
    description: 'Direct replacement left headlight assembly for improved visibility.',
    price: 150.00,
    imageUrl: 'https://picsum.photos/300/200?random=11',
    category: 'Lighting',
    make: 'Mazda',
    model: '3',
    year: 2020,
    vehicleType: 'Sedan',
    shopId: 'supplier-1',
    shopName: DUMMY_SUPPLIERS[0].name,
    quantityAvailable: 6,
  },
  {
    id: '12',
    partNumber: 'FPM-1212',
    name: 'Fuel Pump Module',
    description: 'High-quality fuel pump module for consistent fuel delivery.',
    price: 130.50,
    imageUrl: 'https://picsum.photos/300/200?random=12',
    category: 'Fuel System',
    make: 'GMC',
    model: 'Sierra',
    year: 2017,
    vehicleType: 'Truck',
    shopId: 'supplier-2',
    shopName: DUMMY_SUPPLIERS[1].name,
    quantityAvailable: 4,
  },
];